name: "Cargo Publish"

author: "ryohidaka"

description: "GitHub Actions to publish Rust crates to crates.io."

branding:
  color: green
  icon: send

inputs:
  path:
    description: "The path to the Cargo project root."
    required: false
    default: "."

  token:
    description: "The token to publish to crates.io."
    required: true

  dry-run:
    description: "If true, run cargo publish with the --dry-run flag."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Publish to crates.io
      run: |
        $GITHUB_ACTION_PATH/scripts/publish.sh \
          "${{ inputs.path }}" \
          "${{ inputs.token }}" \
          "${{ inputs.dry-run }}"
      shell: bash
